# Site
repository: VitoOsyko/VitoOsyko.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name:  Осыко Виталий
title: Project Manager
email: vitalyasroma@gmail.com

# Dark Mode (true/false/never)
darkmode: true

github_username:  VitoOsyko
linkedin_username: vitaly-osyko-09248a247
telegram_username: Pokrovsky_Vito

# Additional icon links
additional_links:
  - title: Telegram link
    icon: fab fa-telegram (https://fontawesome.com/icons?d=gallery&m=free)
    url: https://t.me/Pokrovsky_Vito
    
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Обо мне
about_profile_image: images/profile.jpg
about_content: |

  Привет! Меня зовут Виталий, мне 27 лет и я Project Manager. Мой путь в IT начался с области тестирования, где я углубил свои знания в теории тестирования и научился применять их на практике. Работа в QA обогатила меня навыками эффективной командной работы и создания качественных коммуникационных связей между отделами.

  Понимание важности не только проверки ПО на соответствие требованиям, но и построения внутренних связей в компании, вдохновило меня на рост в сфере управления проектами. Сейчас, в роли Project Manager, я активно применяю свой опыт и готов постоянно учиться для достижения общих целей. Мой легкий характер, способность к строгому следованию дедлайнам и навыки командной работы делают меня хорошим кандидатом для вашей команды.

  Считаю, что мои навыки и стремление к постоянному развитию могут внести значительный вклад в успешное выполнение проектов вашей компании. Готов обсудить, как я могу принести пользу вашей команде – свяжитесь со мной, перейдя по ссылкам выше. Буду рад стать частью вашей команды и совместно достигать новых высот!

content:
  - title: Мой опыт
    layout: list
    content:
      - layout: left
        title: Outsourcing company ITX
        sub_title: QA Engineer
        caption: Сентябрь 2022
        link: https://www.linkedin.com/in/innadidenko/
        link_text: Reference - QA Manager Inna Didenko
        quote: >
          Решение проблем путем бесконечного тестирования, во имя создания продуктов меняющих правила игры
        description: |
          - UAT-тестирование, функциональное тестирование
          - Тестирование веб-приложений (продуктовая версия: [capital.com](https://capital.com/) и [currency.com](https://currency.com/))
          - Тестирование мобильных приложений (продуктовая версия: приложения Investmate, Crypto Price Widgets, Liveness Check)
          - Тестирование локализации, кросс-платформенное, кросс-браузерное, Smoke-тестирование, тестирование критического пути, регрессионное тестирование, ретесты, Ad-hoc тестирование
          - Тестирование и сбор статистики показов рекламы на финансовых платформах c/без поведенческого таргетного показов ([Investopedia](https://www.investopedia.com/), [FT](https://www.ft.com/), [Bloomberg](https://www.bloomberg.com/))
          - Создание [Тестовой документации](https://drive.google.com/drive/folders/12BRNLBO7HZvBkDHRUMyQr2I7sAFId0Rz?usp=share_link) (чек листы для desctop и mobile browsers: smoke, critical, regression)
          - Оформление баг репортов
          - Составление State & Transition Diagram для мобильных приложений
          - Описание графических элементов для стандартизации тестовой документации 
          - Создания юзер гайда по приложению
          - Участие в предоставлении онбординга для заказчиков
          - Написание еженедельного отчёта о проделаной работе
          
- layout: left
  company: Company name
  link: Link to company (eg. https://google.com)(optional)
  job_title: Job title
  dates: Date Range (eg. November 2016 - present)
  quote: >
   Short description of the company (optional)
  description: | # this will include new lines to allow paragraphs
    Description of role          
          
  - title: Релевантное образование
    layout: list
    content:
      - layout: left
        title: Ksendzov QA course
        sub_title: QA Trainee
        caption: Август 2022 - Present
        link: https://www.linkedin.com/in/vadim-ksendzov-74099837/
        link_text: Reference - Lead QA Vadim Ksendzov
        quote: >
          Per aspera ad astra... Трудный путь от джуниора до ментора коммерческой практики
        description: |
          После длительного периода самостоятельного обучения я решил записаться на курсы Вадима Ксендзова. Помимо технических знаний, я приобрел много 
          
          *<mark>soft skills:</mark>*
          
          ![Soft Skills](images/chrome_jcWxJrhn65.png "SoftSkills")
          
          На курсах было много интересных заданий, выполнение которых вы можете увидеть в моем репозитории на [GitHub](https://github.com/VitoOsyko) и моем [Google Диске](https://drive.google.com/drive/folders/14wouMRFl7Py97EzI_cPdJZvvLyVFh4hy?usp=share_link).
          
          Во время курса я многое узнал и приобрел следующие 
          
          *<mark>hard skills:</mark>*
          
          ![Hard Skills](images/chrome_I8zk12GAVO.png "HardSkills")
          
          Кстати, моя активность на курсе не прошла незамеченной! Я стал ментором коммерческой практики. Мои обязанности включали: проверку заданий, проверку отчетов об ошибках, ответы на вопросы студентов по темам курса, объяснение ошибок, проверка и помощь в выполнении домашних заданий студентов и многое другое...
          
          Я продолжаю усердно учиться, с огнем в глазах изучать новую профессию! Моя основная профессия - *учитель начальных классов*. Что это значит? Что я устойчив к стрессу в любых ситуациях!
  - title: Дорогой HR
    layout: text
    content: | # this will include new lines to allow paragraphs
     Спасибо, что уделили время и рассмотрели мою кандидатуру.
     
     Я создал этот сайт, чтобы продемонстрировать свой интерес к должности `Junior+ Manual QA Engineer` и отвлечь вас от стандартного резюме, созданного по шаблону. Кроме того, этот проект помог мне улучшить навыки HTML.

     Я хочу выразить вам свой интерес к вакансии QA Engineer, которая открыта в вашей компании. Я убежден, что мой опыт и знания в области QA могут принести большую пользу вашей компании.

     Я понимаю, что у вас в вакансии указан опыт работы как минимум от года, в то время как у меня только 8 месяцев коммерческого опыта работы в QA. Однако, я хочу доказать свою готовность и способность успешно выполнять свои обязанности.

     За время моей работы я приобрел не только теоретические знания в области QA, но и практический опыт, работая над коммерческими проектами. Я уверен, что могу принести свой вклад в развитие вашей компании и принимать участие в проектах, чтобы помочь достичь общих целей.

     Я очень заинтересован в возможности работать в вашей компании, и у меня есть желание развиваться в области QA. Я готов взять на себя ответственность за свою работу и прилагать все усилия, чтобы достичь успеха.

     Благодарю вас за ваше время и внимание к моему письму. Я готов ответить на все ваши вопросы и рассмотреть любые предложения, которые вы можете предложить.

     С уважением, Виталий

# Footer
footer_show_references: true
references_title: References on request (@Pokrovsky_Vito)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]